#!/bin/bash

# fail hard and fast even on pipelines
set -eo pipefail

/run.sh norun

echo "Setting up permissions"
sudo chown odoo:odoo -R /var/lib/odoo
#sudo chown odoo:odoo -R /opt/odoo/sources
sudo chown odoo:odoo -R /opt/odoo/additional_addons

echo "Starting Pycharm"
sudo -u odoo /opt/odoo-dev/pycharm-community-5.0.3/bin/pycharm.sh /var/lib/odoo/PycharmProjects/Odoo
