#!/bin/bash

# fail hard and fast even on pipelines
set -eo pipefail

/run.sh norun

echo "Setting up permissions"
sudo chown odoo:odoo -R /opt/odoo-dev/workspace
#sudo chown odoo:odoo -R /opt/odoo/sources
sudo chown odoo:odoo -R /opt/odoo/additional_addons

echo "Starting Eclipse"
/opt/odoo-dev/eclipse/eclipse -data /opt/odoo-dev/workspace 
#-perspective org.python.pydev.ui.PythonPerspective
