#!/bin/bash

# fail hard and fast even on pipelines
set -eo pipefail

echo "Starting Eclipse"
cd /opt/dev/workspace
/opt/dev/eclipse/eclipse -data /opt/dev/workspace 
#-perspective org.python.pydev.ui.PythonPerspective

